/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello

import javafx.application.Application

fun main(args: Array<String>) {
    Application.launch(AppMain::class.java, *args)
}
